# Generated by Django 4.2.30 on 2026-04-25 16:41

from django.db import migrations, models
import django.db.models.deletion
import ticket.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(upload_to=ticket.models.ticket_upload_path)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='event_registration.registration')),
            ],
        ),
    ]
