# Generated by Django 4.2.30 on 2026-04-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0001_initial'),
        ('payment', '0002_remove_payment_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='event_registration.registration'),
        ),
    ]
