# Generated by Django 4.2.30 on 2026-04-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_app', '0002_event_price'),
        ('event_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_category', models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('competition', 'Competition'), ('cultural', 'Cultural'), ('sports', 'Sports')], max_length=50)),
                ('html_template', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/backgrounds/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificate_templates/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('attendance', 'Attendance'), ('participation', 'Participation'), ('winner', 'Winner'), ('volunteer', 'Volunteer')], default='attendance', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/%Y/%m/')),
                ('verification_qr', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/')),
                ('verification_url', models.URLField(blank=True)),
                ('verification_hash', models.CharField(help_text='SHA-256 hash for verification', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('generating', 'Generating'), ('generated', 'Generated'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='event_app.event')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='event_registration.registration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['certificate_number'], name='certificate_certifi_cd0c46_idx'), models.Index(fields=['verification_hash'], name='certificate_verific_1316c6_idx'), models.Index(fields=['status'], name='certificate_status_31e804_idx'), models.Index(fields=['student', 'status'], name='certificate_student_16729a_idx')],
                'unique_together': {('student', 'event', 'certificate_type')},
            },
        ),
    ]
